In [24]:
import pandas as pd

In [25]:
def read_csv_file(fileName):
    return pd.read_csv(fileName)

In [29]:
def display_data(df):
    print(df.head())

In [39]:
df = read_csv_file("Fish.csv")
display_data(df)

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340


In [40]:
one_hot = pd.get_dummies(df['Species'])  #one hot encoding https://stackoverflow.com/a/39287161/3863545
df = df.drop('Species',axis = 1)
df = df.join(one_hot)
display_data(df)

   Weight  Length1  Length2  Length3   Height   Width  Bream  Parkki  Perch  \
0   242.0     23.2     25.4     30.0  11.5200  4.0200      1       0      0   
1   290.0     24.0     26.3     31.2  12.4800  4.3056      1       0      0   
2   340.0     23.9     26.5     31.1  12.3778  4.6961      1       0      0   
3   363.0     26.3     29.0     33.5  12.7300  4.4555      1       0      0   
4   430.0     26.5     29.0     34.0  12.4440  5.1340      1       0      0   

   Pike  Roach  Smelt  Whitefish  
0     0      0      0          0  
1     0      0      0          0  
2     0      0      0          0  
3     0      0      0          0  
4     0      0      0          0  


In [34]:
X_df = df.loc[ : , df.columns != 'Weight']
display_data(X_df)

   Length1  Length2  Length3   Height   Width  Bream  Parkki  Perch  Pike  \
0     23.2     25.4     30.0  11.5200  4.0200      1       0      0     0   
1     24.0     26.3     31.2  12.4800  4.3056      1       0      0     0   
2     23.9     26.5     31.1  12.3778  4.6961      1       0      0     0   
3     26.3     29.0     33.5  12.7300  4.4555      1       0      0     0   
4     26.5     29.0     34.0  12.4440  5.1340      1       0      0     0   

   Roach  Smelt  Whitefish  
0      0      0          0  
1      0      0          0  
2      0      0          0  
3      0      0          0  
4      0      0          0  


In [35]:
Y = df['Weight']
Y

0      242.0
1      290.0
2      340.0
3      363.0
4      430.0
       ...  
154     12.2
155     13.4
156     12.2
157     19.7
158     19.9
Name: Weight, Length: 159, dtype: float64

In [41]:
import torch
import torch.nn as nn
import numpy as np

In [42]:
feature_data = np.array(df)
feature_data

array([[242. ,  23.2,  25.4, ...,   0. ,   0. ,   0. ],
       [290. ,  24. ,  26.3, ...,   0. ,   0. ,   0. ],
       [340. ,  23.9,  26.5, ...,   0. ,   0. ,   0. ],
       ...,
       [ 12.2,  12.1,  13. , ...,   0. ,   1. ,   0. ],
       [ 19.7,  13.2,  14.3, ...,   0. ,   1. ,   0. ],
       [ 19.9,  13.8,  15. , ...,   0. ,   1. ,   0. ]])

In [45]:
train_dataset, test_dataset = torch.utils.data.random_split(feature_data, [.8, .2])

In [82]:
X = torch.tensor(np.array(train_dataset)[:, 1:-1], dtype=torch.float32)
np_y = np.array(train_dataset)[:, 0]
Y = torch.tensor(np_y.reshape(128, 1), dtype=torch.float32)

In [66]:
n_samples, n_features = X.shape

In [67]:
n_samples, n_features

(128, 11)

In [68]:
input_size = n_features
output_size = 1

In [69]:
learning_rate = .00001
n_iter = 5000

In [70]:
model = nn.Linear(input_size, output_size)

In [71]:
loss = nn.MSELoss()

In [72]:
optimizer = torch.optim.SGD(model.parameters(), learning_rate)

In [83]:
for epoch in range(n_iter):
    y_hat = model(X)
    l = loss(Y, y_hat)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

In [84]:
X[0]

tensor([42.0000, 45.0000, 48.0000,  6.9600,  4.8960,  0.0000,  0.0000,  0.0000,
         1.0000,  0.0000,  0.0000])

In [85]:
Y[0]

tensor([500.])

In [86]:
model(X[0])

tensor([674.4850], grad_fn=<AddBackward0>)

In [87]:
model(X[1])

tensor([184.6086], grad_fn=<AddBackward0>)

In [88]:
Y[1]

tensor([9.8000])

In [90]:
df.iloc[0]

Weight       242.00
Length1       23.20
Length2       25.40
Length3       30.00
Height        11.52
Width          4.02
Bream          1.00
Parkki         0.00
Perch          0.00
Pike           0.00
Roach          0.00
Smelt          0.00
Whitefish      0.00
Name: 0, dtype: float64

In [93]:
X[0]

tensor([42.0000, 45.0000, 48.0000,  6.9600,  4.8960,  0.0000,  0.0000,  0.0000,
         1.0000,  0.0000,  0.0000])