In [24]:
import pandas as pd

In [98]:
df = pd.read_csv("Fish.csv") #data source downloaded from https://www.kaggle.com/datasets/aungpyaeap/fish-market

In [99]:
df.shape

(159, 7)

In [100]:
one_hot = pd.get_dummies(df['Species'])  #one hot encoding https://stackoverflow.com/a/39287161/3863545
df = df.drop('Species',axis = 1)
df = df.join(one_hot)
df.head()

Weight  Length1  Length2  Length3   Height   Width  Bream  Parkki  Perch  \
0   242.0     23.2     25.4     30.0  11.5200  4.0200      1       0      0   
1   290.0     24.0     26.3     31.2  12.4800  4.3056      1       0      0   
2   340.0     23.9     26.5     31.1  12.3778  4.6961      1       0      0   
3   363.0     26.3     29.0     33.5  12.7300  4.4555      1       0      0   
4   430.0     26.5     29.0     34.0  12.4440  5.1340      1       0      0   

   Pike  Roach  Smelt  Whitefish  
0     0      0      0          0  
1     0      0      0          0  
2     0      0      0          0  
3     0      0      0          0  
4     0      0      0          0

In [101]:
import torch
import torch.nn as nn
import numpy as np

In [103]:
feature_data = np.array(df)
feature_data, feature_data.shape

(array([[242. ,  23.2,  25.4, ...,   0. ,   0. ,   0. ],
        [290. ,  24. ,  26.3, ...,   0. ,   0. ,   0. ],
        [340. ,  23.9,  26.5, ...,   0. ,   0. ,   0. ],
        ...,
        [ 12.2,  12.1,  13. , ...,   0. ,   1. ,   0. ],
        [ 19.7,  13.2,  14.3, ...,   0. ,   1. ,   0. ],
        [ 19.9,  13.8,  15. , ...,   0. ,   1. ,   0. ]]),
 (159, 13))

In [104]:
train_dataset, test_dataset = torch.utils.data.random_split(feature_data, [.8, .2])

In [105]:
X = torch.tensor(np.array(train_dataset)[:, 1:], dtype=torch.float32)
np_y = np.array(train_dataset)[:, 0]
Y = torch.tensor(np_y.reshape(128, 1), dtype=torch.float32)

In [106]:
X.shape, Y.shape

(torch.Size([128, 12]), torch.Size([128, 1]))

In [107]:
n_samples, n_features = X.shape

In [108]:
n_samples, n_features

(128, 12)

In [109]:
input_size = n_features
output_size = 1

In [110]:
learning_rate = .00001
n_iter = 5000

In [111]:
model = nn.Linear(input_size, output_size)

In [112]:
loss = nn.MSELoss()

In [113]:
optimizer = torch.optim.SGD(model.parameters(), learning_rate)

In [114]:
for epoch in range(n_iter):
    y_hat = model(X)
    l = loss(Y, y_hat)
    l.backward()
    optimizer.step()
    optimizer.zero_grad()

In [115]:
X[0]

tensor([ 9.3000,  9.8000, 10.8000,  1.7388,  1.0476,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  1.0000,  0.0000])

In [116]:
Y[0]

tensor([6.7000])

In [117]:
model(X[0])

tensor([141.5936], grad_fn=<AddBackward0>)

In [118]:
model(X[1])

tensor([691.5803], grad_fn=<AddBackward0>)

In [119]:
Y[1]

tensor([925.])

In [121]:
df.iloc[0].values

array([242.  ,  23.2 ,  25.4 ,  30.  ,  11.52,   4.02,   1.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ])

In [123]:
model(torch.tensor([23.2 ,  25.4 ,  30.  ,  11.52,   4.02,   1.  ,   0.  ,
         0.  ,   0.  ,   0.  ,   0.  ,   0.  ], dtype=torch.float32))

tensor([440.1643], grad_fn=<AddBackward0>)